---
ntp::servers:
  - 1.us.pool.ntp.org
  - 0.us.pool.ntp.org
  
users_users:
  user:
    ensure: present
    uid: 1000
    comment: 'root@%{::clientcert}'
    managehome: true
    shell: '/bin/bash'
    password: '*'
#    ssh_authorized_keys:
#      Clave_juan_Juan:
#      ensure: present
#      type: 'ssh-rsa'
#        key: ''
  